### PR TITLE
Reduce DOM overload

### PR DESCRIPTION
**Pull request by ghetolay**
We could reduce the output DOM by removing some div and directly use the component element.

For Accordion this would go from : 

``` html
<accordion>
<div class="panel-group" role="tablist" aria-multiselectable="true">
    ....
</div>
</accordion>
```

to

``` html
<accordion class="panel-group" role="tablist" aria-multiselectable="true">
    ....
</accordion>
```

And for AccordionGroup from : 

``` html
<accordion-group>
<div class="panel panel-default">
    <div class="panel-heading" role="tab">
      <h4 class="panel-title">
        <a role="button" data-toggle="collapse" attr.aria-expanded="false">
            ....
        </a>
      </h4>
    </div>
    <div  class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading">
      <div class="panel-body">
        ....
      </div>
    </div>
  </div>
</accordion-group>
```

to

``` html
<accordion-group class="panel panel-default">
    <div class="panel-heading" role="tab">
      <h4 class="panel-title">
        <a role="button" data-toggle="collapse" attr.aria-expanded="false">
            ....
        </a>
      </h4>
    </div>
    <div  class="panel-collapse collapse" role="tabpanel" aria-labelledby="heading">
      <div class="panel-body">
        ....
      </div>
    </div>
</accordion-group>
```

This isn't big but I guess it's enough to worth the change.

About the implementation it may seems weird to add Class's fields through the use of `HostBinding` for purely static values but it's seems to be the way to do it. This may be optimized on aot compilation, I don't know.

### CODE REVIEW

**Comment by pleerock** [comment]
I appreciate your efforts on this, but to be honest I dont see any good points in these changes. You reduced only one line in the dom, but instead we have more complicated code, we have less understandable code, we have less efficient code, we have less declarative code. Does all this worth reducing one line in the DOM? I think no

**Comment by ghetolay** [comment]
Ok my bad I'm pretty sure at some point the `@Component`'s `host` property was flagged as deprecated and said we had to use `HostBinding`.

Now that Angular 2 is officially released [we can see host property is maintained](https://angular.io/docs/ts/latest/api/core/index/Component-decorator.html). Each host's properties will be replaced during compilation with just a `setElementAttribute()`, no more Class property nor change detection check like for proper bindings.

Is it better for you that way ?

**Comment by ghetolay** [comment]
We could also set `display: block` using `host` instead of `styles` : 

``` js
host: {
    style: "display: block;"
}
```

Both source and output code will get cleaner but doesn't seem the good way to do it (can't overrule style wihtout `!important`)

**Comment by pleerock** [comment]
no matter if it is HostBinding or host, it does not change anything. Drawbacks of these changes are still the same:

> You reduced only one line in the dom, but instead we have more complicated code, we have less understandable code, we have less efficient code, we have less declarative code

**Comment by ghetolay** [comment]
Well I don't think that going from 

``` ts
@Component({
    selector: "accordion",
    template: `
        <div class="panel-group" aria-multiselectable="true" role="tablist">
            <ng-content></ng-content>
       </div>
   `
})
```

to 

``` ts
@Component({
    selector: "accordion",
    host: {
        class: "panel-group",
        "aria-multiselectable": "true",
        role: "tablist"
    }
    template: "<ng-content></ng-content>"
})
```

makes code more complicated, less understandable and less efficient.
Would even be tempted to say the opposite.

Anyway you decide.

**Pull request closed without merging**
